{% set name = "pip-api" %}
{% set version = "0.0.27" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pip-api-{{ version }}.tar.gz
  sha256: 354825f2fa89b9b1c56e943be32823c09590e13055a57af5590456ff7d6524bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pip
    - python >=3.6

test:
  imports:
    - pip_api
    - pip_api._vendor
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/di/pip-api
  summary: An unofficial, importable pip API
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Since [`pip`](https://pypi.org/p/pip) is a command-line-tool, [it does not have
    an official, supported, _importable_
    API](https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program).

    However, this does not mean that people haven't tried to `import pip`, usually
    to end up with much headache when `pip`'s maintainers do routine refactoring.

    This project attempts to provide an importable `pip` API, which is _fully
    compliant_ with the recommended method of using `pip` from your program.
  doc_url: http://github.com/di/pip-api
  dev_url: http://github.com/di/pip-api

extra:
  recipe-maintainers:
    - sugatoray
